git_repo: git@gitlab.com:travelogue/traveldb-api.git

project_name: traveldb-api
application_name: traeveldbapi

project_path: /var/www/{{ project_name }}

git_branch: master


# Database settings.
db_user: "{{ application_name }}"
db_name: "{{ application_name }}"
db_password: okaythisshouldprobablybegenerated
