---

- name: Install virtualenv
  pip: name=virtualenv executable=pip3

- name: Create the virtualenv
  become_user: "{{ application_user }}"
  command: virtualenv -p {{ virtualenv_python_version }} {{ virtualenv_path }}
           creates={{ virtualenv_path }}/bin/activate

- name: Install packages for django_app
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}

- name: Create virtualenv postactivate script
  template: src=virtualenv_postactivate.j2
            dest={{ virtualenv_path }}/bin/postactivate
            owner={{ application_user }}
            group={{ application_group }}
            mode=0640
            backup=yes
