---

- include: create_users_groups.yml

- include: setup_git_repo.yml

- include: create_virtualenv.yml

- name: Generate env_settings for application
  template: src=env_settings.py.j2
            dest={{ project_path }}/api/env_settings.py
            owner={{ application_user }}
            group={{ application_user }}
            backup=yes
  tags: django

- name: Set up initial migrations for db
  django_manage:
    command: migrate
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  tags: django