---

- include: create_users_groups.yml

- include: setup_git_repo.yml

- include: create_virtualenv.yml

- name: Ensure application group owns application directory
  file: 
    dest={{ project_path }} 
    owner={{ application_user }}
    group={{ application_group }}
    recurse=true

- name: Generate env_settings for application
  template: src=env_settings.py.j2
            dest={{ project_path }}/traveldb/env_settings.py
            owner={{ application_user }}
            group={{ application_user }}
            backup=yes
  tags: django

- name: Set up initial migrations for db
  django_manage:
    command: migrate
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  tags: django