---

- include: create_users_groups.yml

- include: create_virtualenv.yml

- name: Set up root directory
  file: path=/root/ state=directory

- name: Set up root ssh directory
  file: path=/root/.ssh/ state=directory

- name: Set up ssh public key
  copy: src=./deploy_key.pub
        dest=/root/.ssh/id_rsa.pub
        mode=0644

- name: Set up ssh private key
  copy: src=./deploy_key
        dest=/root/.ssh/id_rsa
        mode=0600

- name: Clone git repo
  git: repo={{ git_repo }} dest={{ project_path }} accept_hostkey=yes

- name: Generate env_settings for application
  template: src=env_settings.py.j2
            dest={{ project_path }}/api/env_settings.py
            owner={{ application_user }}
            group={{ application_user }}
            backup=yes

- name: Set up initial migrations for db
  django_manage:
    command: migrate
    app_path: "{{ project_path }}"